const languageCodes = {
  en: "English",
  ur: "Urdu",
  es: "Spanish",
  fr: "French",
  de: "German",
  ru: "Russian",
  zh: "Chinese",
  ja: "Japanese",
  ko: "Korean",
  hi: "Hindi",
  ar: "Arabic",
  pt: "Portuguese",
  it: "Italian",
  nl: "Dutch",
  pl: "Polish",
  tr: "Turkish",
  vi: "Vietnamese",
  th: "Thai",
  ms: "Malay",
  id: "Indonesian",
  ro: "Romanian",
  fa: "Persian",
  he: "Hebrew",
  sv: "Swedish",
  cs: "Czech",
  uk: "Ukrainian",
  hu: "Hungarian",
  bn: "Bengali",
  ta: "Tamil",
  te: "Telugu",
  mr: "Marathi",
  gu: "Gujarati",
};

export default languageCodes;
